### ISSUE TITLE
Get undefined value

### ISSUE THREAD

**Issue by NikDevx** [NikDevx/homebridge-philips-air#164]
Hello @Sunoo 
I need your help.
How to pass data to this one :
```
on('get', (callback: CharacteristicGetCallback) => {
          this.enqueueAccessory(CommandType.GetStatus, accessory);
          callback();
        });
```
I can comment on this part of the code, but this will not update the state of the accessory.

Full functuon:
```
      purifierService
        .getCharacteristic(hap.Characteristic.Active)
        .on('set', async(state: CharacteristicValue, callback: CharacteristicSetCallback) => {
          try {
            await this.setPower(accessory, state);
            callback();
          } catch (err) {
            callback(err);
          }
        }).on('get', (callback: CharacteristicGetCallback) => {
          this.enqueueAccessory(CommandType.GetStatus, accessory);
          callback();
        });
```

It's always `undefined`

`[09.04.2021, 15:31:10] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.`

**Comment by Sunoo** [comment]
The way I designed this, to keep performance up, was to stick the command in a queue and then immediately call the callback. Then, when the command actually ran, it would manually update the status in HomeKit.

Unfortunately, Homebridge 1.3 is more strict about following the HomeKit spec. You could simply ignore those warnings, since things should still work. Or, you could cache the current value somewhere and call the callback with the cached value. Or you could rework the way this whole process functions so you can call the callback with a value some other way.

**Comment by NikDevx** [comment]
Okay
Thanks!
I have already changed the polling and status update function.
Now I can comment out this part of the code
```
.on('get', (callback: CharacteristicGetCallback) => {
          this.enqueueAccessory(CommandType.GetStatus, accessory);
          callback();
        });
```

**Comment by Sunoo** [comment]
Great, yea. Just polling without actually handling get requests is probably a better approach anyways.
